ServerConfig:
  AppVersion: 1.0.0
  Mode: Development
  RoutePrefix: /api/v1
  Debug: false
  Port: 8080
  TimeoutSecs: 60
  ReadTimeoutSecs: 60
  WriteTimeoutSecs: 12

JWTConfig:
  SessionTime: 3600
  SecretKey: dummySecretKey

DBConfig:
  DataSourceName: postgres://postgres:000000@localhost:5432/eCommerce?sslmode=disable
  MaxOpen: 50
  MaxIdle: 50
  MaxLifetime: 5



Logger:
  Development: true
  Encoding: json
  Level: info
